---
version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
      time: "14:00"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
    allow:
      - dependency-type: all

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
      time: "14:00"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
    allow:
      - dependency-type: all

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "14:00"
    cooldown:
      default-days: 7

  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: daily
      time: "14:00"
    cooldown:
      default-days: 7
